# Generated by Django 4.2.20 on 2025-03-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('NISSAN', 'NISSAN'), ('Audi', 'Audi'), ('Porsche', 'Porsche'), ('Ford', 'Ford'), ('Nord Motion', 'Nord Motion'), ('Mercedez Benz', 'Mercedez Benz'), ('Toyota', 'Toyota')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('fuel_efficiency', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gps_navigation', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sitepages.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_datetime', models.DateTimeField()),
                ('first_name', models.CharField(default='unknown', max_length=100)),
                ('last_name', models.CharField(default='unknown', max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('mobile_number', models.CharField(default='unknown', max_length=15)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('rental_days', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitepages.cars')),
                ('drop_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_bookings', to='sitepages.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='sitepages.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
