apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-deployment
  labels:
    app: car-rental
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental
  template:
    metadata:
      labels:
        app: car-rental
    spec:
      containers:
      - name: car-rental
        image: 783744717866.dkr.ecr.us-east-2.amazonaws.com/car-rental-app:latest  # Your ECR image
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "car_rental.settings"
        - name: DEBUG
          value: "True"

