apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
  labels:
    app: car-rental
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: car-rental

